; PlatformIO Project Configuration
; Akıllı Kilit Projesi - Parmak İzi Firmware (ESP32-C3)
; -----------------------------------------------------------------------------

[env:esp32dev]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200

; C3 modelinde USB-CDC seri portu için gerekli bayrak
build_flags = 
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
monitor_dtr = 1
monitor_rts = 1
monitor_filters = esp32_exception_decoder, default

lib_deps =
    adafruit/Adafruit Fingerprint Sensor Library@=2.1.0
    marcoschwartz/LiquidCrystal_I2C@^1.1.2
