; PlatformIO Project Configuration
; Akıllı Kilit Projesi - Parmak İzi Firmware (ESP32-C3)
; -----------------------------------------------------------------------------

[env:esp32dev]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200

; C3 modelinde USB-CDC seri portu için gerekli bayrak
build_flags = 
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1

lib_deps =
    adafruit/Adafruit Fingerprint Sensor Library@=2.1.0
    adafruit/Adafruit SSD1306@^2.5.7
    adafruit/Adafruit GFX Library@^1.11.5

; Mock mod aktif (donanım bağlanana kadar test için)
[env:esp32dev_mock]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
build_flags = 
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DMOCK_MODE
lib_deps =
    adafruit/Adafruit Fingerprint Sensor Library@=2.1.0
    adafruit/Adafruit SSD1306@^2.5.7
    adafruit/Adafruit GFX Library@^1.11.5
