; PlatformIO Project Configuration
; Akıllı Kilit Projesi - Parmak İzi Firmware (ESP32 DevKit)
; -----------------------------------------------------------------------------

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

monitor_filters = esp32_exception_decoder, default

lib_deps =
    adafruit/Adafruit Fingerprint Sensor Library@=2.1.0
    marcoschwartz/LiquidCrystal_I2C@^1.1.2
